# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: min_max_repeat.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("min_max_repeat.proto", :syntax => :proto3) do
    add_message "MinMaxParams" do
      repeated :value, :float, 1
    end
    add_message "MinMaxReply" do
      optional :min, :float, 1
      optional :max, :float, 2
    end
  end
end

MinMaxParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MinMaxParams").msgclass
MinMaxReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MinMaxReply").msgclass
