/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LAB1_RPC_2_WORKERS_H_RPCGEN
#define _LAB1_RPC_2_WORKERS_H_RPCGEN

#include <rpc/rpc.h>

#include <sys/wait.h>
#include <unistd.h>
#include <semaphore.h>
#include <sys/mman.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct SharedData {
	float min1, min2;
	float max1, max2;
} SharedData;

struct params {
	float *v;
	int n;
};
typedef struct params params;

struct result {
	float min;
	float max;
};
typedef struct result result;

#define PROG 44444444
#define VERSAO 100

#if defined(__STDC__) || defined(__cplusplus)
#define MIN_MAX 1
extern  result * min_max_100(params *, CLIENT *);
extern  result * min_max_100_svc(params *, struct svc_req *);
extern int prog_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MIN_MAX 1
extern  result * min_max_100();
extern  result * min_max_100_svc();
extern int prog_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_params (XDR *, params*);
extern  bool_t xdr_result (XDR *, result*);

#else /* K&R C */
extern bool_t xdr_params ();
extern bool_t xdr_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LAB1_RPC_2_WORKERS_H_RPCGEN */
