/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "lab1_rpc_2_workers.h"

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <pthread.h>

#define NUM_THREADS 7

typedef struct ThreadParam {
	float * v;
	int limits[2];
	result result;
} ThreadParam;

result find_min_max(float * v, int s, int e) {
	result result;

	result.min = v[s];
	result.max = v[s];

	for (int i = s + 1; i < e; i++) {
    if (v[i] < result.min)
      result.min = v[i];

    if (v[i] > result.max)
      result.max = v[i];
  }

	return result;
}

void * thread_worker(ThreadParam * param) {
	param->result = find_min_max(param->v, param->limits[0], param->limits[1]);

	pthread_exit(NULL);
}

result *
min_max_100_svc(params *argp, struct svc_req *rqstp)
{
	static result result;
  ThreadParam args[NUM_THREADS];
  pthread_t threads[NUM_THREADS];

	float thread_results[NUM_THREADS * 2];

  for (int i = 0; i < NUM_THREADS; i++) {
		args[i].v = argp->v;

    for (int j = 0; j < 2; j++) {
      args[i].limits[j] = ((i + j) * argp->n) / NUM_THREADS;
    }

    pthread_create(&threads[i], NULL, (void *) thread_worker, (void *) &args[i]);
  }

	int count = -1;

  for (int i = 0; i < NUM_THREADS; i++) {
    pthread_join(threads[i], NULL);

		thread_results[++count] = args[i].result.min;
		thread_results[++count] = args[i].result.max;
  }

	result = find_min_max(thread_results, 0, NUM_THREADS * 2);

	return &result;
}
