/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "lab1_rpc_2_workers.h"

extern sem_t * mutex;
extern SharedData * shared_data;

// typedef struct SharedData {
// 	float min1, min2;
// 	float max1, max2;
// } SharedData;

// static sem_t * mutex = NULL;

// static SharedData * shared_data = NULL;

// void handle_failure(int rt, char message[]) {
//   if (rt < 0) {
//     fprintf(stdout, "%s\n", message);
//     exit(1);
//   }
// }

// void init_shared() {
//   // place our shared data in shared memory
//   int prot = PROT_READ | PROT_WRITE;
//   int flags = MAP_SHARED | MAP_ANONYMOUS;
//   mutex = mmap(NULL, sizeof(sem_t), prot, flags, -1, 0);
// 	shared_data = mmap(NULL, sizeof(SharedData), prot, flags, -1, 0);

// 	shared_data->min1 = -1;
// 	shared_data->min2 = -1;
// 	shared_data->max2 = -1;
// 	shared_data->max2 = -1;

//   handle_failure(mutex == MAP_FAILED ? -1 : 0, "Não conseguiu alocar memória");

// 	handle_failure(shared_data == MAP_FAILED ? -1 : 0, "Não conseguiu alocar memória");

//   sem_init(mutex, 1, 1);
// }


result get_min_max(float * v, int start, int end) {
	result result = { .min = v[start], .max = v[start] };

  for (int i = start; i < end; i++) {
    if (v[i] < result.min)
      result.min = v[i];

    if (v[i] > result.max)
      result.max = v[i];
  }

	result;
}

result *
min_max_100_svc(params *argp, struct svc_req *rqstp)
{
	static result  result;

	// init_shared();

  pid_t pid = fork();
  // handle_failure(pid, "Não foi possível criar um processo filho\n");

  if (pid > 0) {
		struct result calc1 = get_min_max(argp->v, 0, argp->n / 2);

		sem_wait(mutex);

		shared_data->min1 = calc1.min;
		shared_data->max1 = calc1.max;

		sem_post(mutex);

		wait(NULL);

		float list[4];
		calc1 = get_min_max(list, 0, 3);

		result = calc1;

		return &result;
  } else {
		struct result calc2 = get_min_max(argp->v, argp->n / 2, argp->n);

		sem_wait(mutex);

		shared_data->min2 = calc2.min;
		shared_data->max2 = calc2.max;

		sem_post(mutex);

		exit(0);
  }

	return &result;
}
