/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "lab1_rpc_2_workers.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

sem_t * mutex;
SharedData * shared_data;

void handle_failure(int rt, char message[]) {
  if (rt < 0) {
    fprintf(stdout, "%s\n", message);
    exit(1);
  }
}

void init_shared() {
  // place our shared data in shared memory
  int prot = PROT_READ | PROT_WRITE;
  int flags = MAP_SHARED | MAP_ANONYMOUS;
  mutex = mmap(NULL, sizeof(sem_t), prot, flags, -1, 0);
	shared_data = mmap(NULL, sizeof(SharedData), prot, flags, -1, 0);

	shared_data->min1 = -1;
	shared_data->min2 = -1;
	shared_data->max2 = -1;
	shared_data->max2 = -1;

  handle_failure(mutex == MAP_FAILED ? -1 : 0, "Não conseguiu alocar memória");

	handle_failure(shared_data == MAP_FAILED ? -1 : 0, "Não conseguiu alocar memória");

  sem_init(mutex, 1, 1);
}

static void
prog_100(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		params min_max_100_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case MIN_MAX:
		_xdr_argument = (xdrproc_t) xdr_params;
		_xdr_result = (xdrproc_t) xdr_result;
		local = (char *(*)(char *, struct svc_req *)) min_max_100_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (PROG, VERSAO);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PROG, VERSAO, prog_100, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PROG, VERSAO, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PROG, VERSAO, prog_100, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PROG, VERSAO, tcp).");
		exit(1);
	}

	init_shared();

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
