# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: min_max.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("min_max.proto", :syntax => :proto3) do
    add_message "Element" do
      optional :value, :float, 1
    end
    add_message "MinMaxReply" do
      optional :min, :float, 1
      optional :max, :float, 2
    end
  end
end

Element = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Element").msgclass
MinMaxReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MinMaxReply").msgclass
