# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: sum.proto for package ''

require 'grpc'
require_relative 'sum_pb'

module Sum
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Sum'

    rpc :SumCalc, ::SumParams, ::SumReply
    rpc :SumArrayCalc, stream(::SumArrayParam), ::SumReply
    rpc :SumByteArrayCalc, ::SumByteArrayParam, ::SumReply
  end

  Stub = Service.rpc_stub_class
end
